/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RosterIndexRouteImport } from './routes/roster.index'
import { Route as RosterFileIdRouteImport } from './routes/roster.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIndexRoute = RosterIndexRouteImport.update({
  id: '/roster/',
  path: '/roster/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterFileIdRoute = RosterFileIdRouteImport.update({
  id: '/roster/$fileId',
  path: '/roster/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roster/$fileId': typeof RosterFileIdRoute
  '/roster/': typeof RosterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/roster/$fileId': typeof RosterFileIdRoute
  '/roster': typeof RosterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roster/$fileId': typeof RosterFileIdRoute
  '/roster/': typeof RosterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/roster/$fileId' | '/roster/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/roster/$fileId' | '/roster'
  id: '__root__' | '/' | '/roster/$fileId' | '/roster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RosterFileIdRoute: typeof RosterFileIdRoute
  RosterIndexRoute: typeof RosterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/': {
      id: '/roster/'
      path: '/roster'
      fullPath: '/roster/'
      preLoaderRoute: typeof RosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$fileId': {
      id: '/roster/$fileId'
      path: '/roster/$fileId'
      fullPath: '/roster/$fileId'
      preLoaderRoute: typeof RosterFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RosterFileIdRoute: RosterFileIdRoute,
  RosterIndexRoute: RosterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
